language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - sudo pip install --use-mirrors pyinstaller
  - make clean
  - make
  - python -m unittest discover
  - dpkg-buildpackage -tc
  - sudo dpkg -i ../jpylyzer_1.10.1_amd64.deb
script:
  - python -m unittest discover
